name: Example

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Julia from URL
        uses: julia-actions/install-julia-from-url@main
        with:
          url: https://julialangnightlies.s3.amazonaws.com/bin/linux/x64/1.6/julia-377aa809eb-linux64.tar.gz

      - name: Show versioninfo()
        run: julia -e "using InteractiveUtils; versioninfo()"
