name: Example

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Julia from URL
        uses: ./
        with:
          url: https://s3.amazonaws.com/julialangnightlies/assert_pretesting/freebsd/x64/1.7/julia-4e6a3a4140-freebsd64.tar.gz

      - name: Show versioninfo()
        run: julia -e "using InteractiveUtils; versioninfo()"
